language: node_js
node_js: node
jobs:
  include:
    - stage: Unit tests
      script:
      - npm run lint
      - |
        if [ $TRAVIS_PULL_REQUEST != false ] && [ $TRAVIS_SECURE_ENV_VARS == true ]; then
            echo "Pull request with secure environment variables, running Sauce tests...";
            npm run test:sauce || travis_terminate 1;
        else
            echo "Not a pull request and/or no secure environment variables, running headless tests...";
            npm run test:headless || travis_terminate 1;
        fi
      env:
        - SAUCE_USERNAME: Gaudi1
        # SAUCE_ACCESS_KEY
        - secure: QYfjasquwtyUakYPOMjde7YfEawbW71fX2F4rtxTUaKBZy+sKp9xPEA/0p3L/lNumHLMuvTfLuRhNWJ3Ag5gahka1DO40Fr5zXN4aIyzUvbFkAcp46AvaYibFEn7SzAkbGSE3pSGWEESdC/Dq6eokQvvn28jyO8LAn5nW+Dlhsh21HjDsLdlsogjpVznOLl8WRFEsryW6m4kxy4F+K9XycBPAfgyNOm/4B/bmWUmZCem1rjmBQRQ5Y6DSTDJ02TEbUQg2IJEosEDJy4GXeq3jOTwDKY953VbNcLispGnVZKfH1BOnvqbdNkVRhw6q5Wc7eUr8gl+ifr6oCHDSY6S0ot7bVSe/LLjL+ZUXS0L5KV4pMCQgqe2Nltld57GcPJZBsVXu4+RLpYGz+PIz0IEg17aRSm+SxMVd37H30fZ7O1tgisGN5cFq9cqBX7Jtzn8xhAtyT1TyzgQTIpVaHS7ry6P1iuCJTTT4A0Tt2gl7aBeNlvttWl6ZB3lIr5FoTAqM+JOQG7dxgmQXrVe5Gh/vhbFQHFW6DX292u3odJ70Vxy4lDb3pEO8EDKSiSJXTlv25GijaK9AJ4jU7GS6a6ibojLHB4+yuhDF2nfgPxF9mHc8jynPhOu42OWGfkOysY1xHVvRYIuhaLdnqjO6Sx8LTTpoJw0aVS63DO69mf3B8M=
    - stage: Visual-difference-tests
      script:
      - if [ $TRAVIS_SECURE_ENV_VARS == true ]; then
          echo "Running visual difference tests...";
          npm run test:diff || travis_terminate 1;
        fi
      env:
        # VISUAL_DIFF_S3_ID
        - secure: kVCTtJVN5OX3HoeoU7uiKaLKhIQwFX0Q5mWUJRA1g8CfCQTFPgHtLPgWUBGMCqNKFsyE2hBtOGLIu7Gx1s7iPm1/vf/4rwgCrFLa2v/HaSH0wa8ACgfp/7eh/ZyL806iZD9RonenI94Oof5mVndVc7iPyMJWWEKfskSkwrzCHPoESTka+VkIpgfXHFggskfd5bcsaZp8kucv1FWq7RQolSiNM5keRJ9EZzPUBpQPg1HtLoYKZUD5B1QVnJbcmANHYBdnuNyNeqw4u8ERKtARmNIjNDHiLBYKKmpVTvkqRY5ksIlmOmj9H4VfPSWVj+dlV9SAYBzg8Zje00MrPSamDx4E0cbKsRXr3QuxM3cqHCCTobodiv4EzQLB8HbrIp4OAq4Aj4hHe/xYFAwZLcIT5lnfpJYHRnYTHkLoojkLVVzXB9TbO4BRtcqIm+r/xycHmD0lwgCnIsrRthnTDuQQl2RlM9qKX5fzB2h/Jdku7NA96FzNeEwBsfkyfasM046l44WdZ1YhQE+ce95/CjvIMrELpMCwQKzX/TCP0WH3MLXibK+Bwt3gicVVVzadTjRlNMdowwpVhXdAxMfcSSIhk3f1jXr/t7AeIenzied1fOymVRAhpmrxlYqOyuGR15xtrozKF550U9Qvvl3Z/9LOA0Y/MKUAU+LSwb9XzrEvk5A=
        # VISUAL_DIFF_S3_SECRET
        - secure: uuQ6qBb4kj7mxyCNjtl5H3GF92Ysc1/y2Q4thqLoIPndgpq5c3ACc3M/pLfw7dcbT37fwNowp93c/tVwwWzwgPwoqmHnW9SMzftBvIe5yVpHYvl+TzSppVVVzFtG180F5Pu8p4TyIbfpmO7Muzfci4BPAvnWFlTgFTwAWgYm5Un1JbduOj0QJEFDnlgsL4Yi/kIcXYgNLtMGaEvk43vEXxJQnGQYz+mhigqBJcQipIS1t1oGPN+EkPRK6Wk6aD/8a8NaG6mzGSLAE6x/6fz8VJZrXVc9F99v4Z17AreIYxKh4Zp7aDY3q8xkDXII4bHclfMLmWgWOLptS51o9KDWEGTyfk0Y6NGp1qOLGfqLYS1eSN76G/Gp8/TYp3iTfn5vWpdZEPcEAj8T6+5vR0Smw7unCPkh9I86uuH+q2cnhied6bPUW+0LSNlFalqXBoTM1Dlc99zGW0Bw0rlYvvs/ww41QFbRth/YMUfcdgrF9QBX39yH6G30uzIoJGZslQdSblyri87huUzZ1Lbjj5iJrwDWsG4GZjZ96jXws+K2D1af0mi5oYrw44LLtsil2FfW5B7b7d0AxDV558PxllT6Lqi5SDjAuy+MP2whvsJbiHqKiKmYZnppaifHbHHUwdVBk14HQw0Z2NtdQLz/sE5UpKpIjzvtcLKWqKW1GQwRuXI=
    - stage: Deploy
      script: exit 0
      after_success: frauci-update-version -d=skip && export TRAVIS_TAG=$(frauci-get-version)
      env:
        - REPO_NAME=htmleditor
        - OWNER_NAME=BrightspaceUI
      deploy:
        provider: npm
        email: d2ltravisdeploy@d2l.com
        skip_cleanup: true
        api_key:
          # 8689......727c
          secure: jeHK6NskXajLitOX3BxJKd6mzoeegeQQOsn60nvwXnQKCmWkay8PaMJ6mkMDQwaCdCqi4r4/jlGyVnfCbAb2gFyt8x1zdBRPqfPg2JEuxRnEc3pV8SWJxYT6PjU2DTQbOhfYtAjevvkjzjMmduBKdmuhtqTd9BZRcguuMbSTHr7aR2T7up5viPmPHFPdga4AZAG0fGW6ece+Ys2dQDqT2YkdhG803HIqPeboTlnEBJconGKxKtqcf97O1gvmUoJaV/++4Tg4mOiFA0TqGA0kmP5rn5+kIjY0GZuOV+kLrL7jaScMB52fLQf+ftJpNlN7RrqIxXE9tbmJZA+qCImf8MjFhUk8wVSsN4ijd4LuXWiqh0t7S4evliOQLjTyRxfIIM0YxbaVVn7O7jcYwujW48NeSinb7nLVN9GerZum3AbT5W5myqbUpS70F5pvxRWJP4HsNuGn97aJU/szjzRDRNGJuB/GZmOlksjyUxi1n7HGaEvxi65dSIcghG7XLLljZyMiG5TDEKZni3FXXzaw8uDazjJOhXqvskj0w0w+71sWXneJTOyT/suGr4ajoPnkxdBtrzCmAV4/PR8OPoUZhLDe/OneH8RPdSoXgw3QjymVSJBhIiqQhq9jJyKUtFrokic3gYcdWgVEkaL9sUBUPG9iCbwi+Tmt4XVGOrO9LTI=
        on:
          repo: BrightspaceUI/htmleditor
          tags: true
env:
  global:
  # GITHUB_RELEASE_TOKEN
  - secure: psgs+unxMmah+He0gFKPPdgxfBufkU447vbu/zVx59/y4YegLJLfqMdvneJkWCbSCmxrz6Vr7Ip7XLUSADIdwHan9L9kWWWb4NmCN/PxBdKPus0EiLLZK6lpH9rOU65OnHvNKcuBFZuj2D1/rS/uf67CwcBscB2DbdwwSe3IuM21zz2/QKtts4walyn4y3dAQZIKVBarvjpq+yJ3OSYUmfulZ857Ustp6bqrftYuyOkrgIs9pGwTDrJ9E48NQwoDP3UDF6r74mwla+WbvZrIYjYHwkY14lR91N+JojeWmBXWQapXHosKBpUTLU3GWvNU7PjbKkJEO+cWkFTc934ThzZYb56htBR+iL4uvCC2yjqk7DsZJki0uVD+WOZu9Al63eeXAsS7fuBu7rr4JWLFIDrYITFdzvpqy3pXXAaVluuVyPyXBc4AqH7tXNfL5H4kan0oZDoRdQtKDYjf9Azep2vy0WxVwdEgNROYSi7rGCHJtgWSMzO/bztrhuSRm3CXHnw3GvfTsABJy5TCnQqS91pbsbssieLnFt7eZW0z5zfw1/OP2A+U29XxungibdJuxAx0fzAnk+cfnzaFK1pzR3NLn1lTMqFIo4kWLavxyTQReNEq1I3OurMjA7PUigLnASxi3K/OSObjcSH2O5L5oNyAR2Sq/RBBn99Tb3xJtbI=
